from turtle import *
def house():
    color('black', '#ff883a')
    begin_fill()
    for i in range(2):
        forward(150)
        left(90)
        forward(75)
        left(90)
    end_fill()
    penup()
    forward(20)
    left(90)
    forward(15)
    pendown()
    color('black' , 'cyan')
    begin_fill()
    for i in range(4):
        forward(45)
        right(90)
    end_fill()
    penup()
    right(90)
    forward(65)
    pendown()
    begin_fill()
    for i in range(4):
        forward(45)
        left(90)
    end_fill()
    forward(22.5)
    left(90)
    forward(45)
    left(90)
    penup()
    forward(65)
    left(90)
    pendown()
    forward(45)
    penup()
    forward(15)
    right(90)
    forward(42.5)
    right(90)
    forward(75)
    pendown()
    begin_fill()
    color('black','#722d00')
    right(30)
    forward(60)
    right(60)
    forward(90)
    right(60)
    forward(60)
    end_fill()


def bighouse():
    color('black', 'gray')
    begin_fill()
    for i in range(2):
        forward(100)
        left(90)
        forward(260)
        left(90)
    end_fill()
    penup()
    forward(20)
    left(90)
    forward(20)
    right(90)
    color('black','cyan')
    for i in range(3):
        pendown()
        begin_fill()
        for i in range(4):
            forward(60)
            left(90)
        end_fill()
        penup()
        left(90)
        forward(80)
        right(90)

def tree():
    color('black', 'brown')
    begin_fill()
    for i in range(2):
        forward(15)
        left(90)
        forward(60)
        left(90)
    end_fill()
    penup()
    left(90)
    forward(60)
    right(90)
    forward(37.5)
    left(90)
    forward(30)
    pendown()
    color('black','green')
    begin_fill()
    circle(30)
    end_fill()
    


